name: Create TODO Issues

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: false
        required: false
        type: boolean
        description: Import all existing todo comments.
  push:

permissions:
  contents: read
  issues: write

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: DerJuulsn/todo-issue@v1.1.4
        with:
          keywords: TODO, FIXME
          blobLines: 15
          caseSensitive: false
          label: true
          reopenClosed: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
